# 🧑‍💻 NumPy Complete Guided Project
**Instructor / Student Colab Notebook** – covers *all* key concepts from `Numpy‑1` to `Numpy‑5`.

*Generated: 08 Aug 2025*


**Table of Contents**

1. [Setup](#setup)  
2. [Array Creation & Dtypes](#creation)  
3. [Array Attributes & Inspection](#attributes)  
4. [Indexing, Slicing, Fancy Indexing](#indexing)  
5. [Reshaping, Transpose & Copies vs Views](#reshape)  
6. [Joining, Splitting, Set & Sorting Ops](#join)  
7. [Arithmetic Ops, Universal Functions](#arithmetic)  
8. [Broadcasting (Rules + Examples)](#broadcast)  
9. [Statistics & Aggregations](#stats)  
10. [Random Numbers & Reproducibility](#random)  
11. [Structured / Recarrays](#structured)  
12. [Linear Algebra Essentials](#linalg)  
13. [File I/O (`npy`, `npz`, `txt`)](#io)  
14. [Datetime64 & Timedelta64](#datetime)  
15. [Masked Arrays & NaNs](#mask)  
16. [Mini‑Project — Fitness Data Analysis](#project)  
17. [Conclusion & Next Steps](#conclusion)  


## <a name='setup'></a>1️⃣ Setup

In [1]:
import numpy as np, math, os, pathlib, types, textwrap, random
print('NumPy version:', np.__version__)

NumPy version: 2.0.2


## <a name='creation'></a>2️⃣ Array Creation & Dtypes

Key functions: `np.array`, `np.arange`, `np.linspace`, `zeros`, `ones`, `full`, `eye`, `identity`, `diag`, `empty`

In [2]:
# EXAMPLE
arr1 = np.array([1, 2, 3], dtype=np.int32)
arr2 = np.linspace(0, 1, 6)
arr3 = np.full((2,3), 7.5)
print(arr1, arr2, arr3, sep="\n")
print("dtypes:", arr1.dtype, arr2.dtype)


[1 2 3]
[0.  0.2 0.4 0.6 0.8 1. ]
[[7.5 7.5 7.5]
 [7.5 7.5 7.5]]
dtypes: int32 float64


In [7]:
# 🖊️ TODO: create a 10×10 chessboard pattern using zeros & ones
arr3=np.arange(10).reshape(-1,1)
arr4=np.arange(10).reshape(1,-1)
arr5=(arr3+arr4)%2

print(arr5)


[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


## <a name='attributes'></a>3️⃣ Array Attributes & Inspection

`shape`, `ndim`, `size`, `dtype`, `itemsize`, `nbytes`

In [8]:
M = np.arange(12).reshape(3,4)
print('shape', M.shape, 'ndim', M.ndim, 'size', M.size, 'itemsize', M.itemsize, 'total bytes', M.nbytes)


shape (3, 4) ndim 2 size 12 itemsize 8 total bytes 96


In [11]:
# 🖊️ TODO: check memory footprint of a 1000×1000 float64 array
arr6=np.zeros((1000,1000),dtype=np.float64)
print("Memory footprint is",arr6.nbytes)

Memory footprint is 8000000


## <a name='indexing'></a>4️⃣ Indexing, Slicing & Fancy Indexing

In [15]:
a = np.arange(1,26).reshape(5,5)
print(a)
print(a[:, 0])     # first column
print(a[::2, ::2]) # every 2nd row/col
mask = (a % 3 == 0)
print('multiples of 3:', a[mask])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  6 11 16 21]
[[ 1  3  5]
 [11 13 15]
 [21 23 25]]
multiples of 3: [ 3  6  9 12 15 18 21 24]


In [16]:
# 🖊️ TODO: use fancy indexing to swap first and last rows of `a`
a[[-1,0]]=a[[0,-1]]
print(a)

[[21 22 23 24 25]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [ 1  2  3  4  5]]


## <a name='reshape'></a>5️⃣ Reshaping, Transpose & Copies vs Views

In [17]:
b = np.arange(8)
B = b.reshape(2,4)
B[0,0] = 99
print('b is modified:', b)
C = b.reshape(2,4).copy()
C[0,0] = -1
print('b unchanged with copy:', b)


b is modified: [99  1  2  3  4  5  6  7]
b unchanged with copy: [99  1  2  3  4  5  6  7]


In [20]:
# 🖊️ TODO: Flatten a 3‑D array into 1‑D using both `ravel` and `flatten`; observe copy vs view.
arr3dim=np.arange(24).reshape(2,3,4)
r = arr3dim.ravel()
f = arr3dim.flatten()
arr3dim[0,0,0]=123
print("after using ravel original array is ",r[0])
print("after using flatten original array is",f[0])

after using ravel original array is  123
after using flatten original array is 0


## <a name='join'></a>6️⃣ Joining, Splitting, Set & Sorting Ops

In [21]:
x = np.array([1,3,5]); y = np.array([2,4,6])
xy = np.concatenate([x,y])
print('union', np.union1d(x,y))
print('intersect', np.intersect1d(xy,[1,2,10]))
print('sorted descending', np.sort(xy)[::-1])


union [1 2 3 4 5 6]
intersect [1 2]
sorted descending [6 5 4 3 2 1]


In [22]:
# 🖊️ TODO: split `xy` back into two equal halves using `np.array_split`
first,second=np.array_split(xy,2)
print(first,second)

[1 3 5] [2 4 6]


## <a name='arithmetic'></a>7️⃣ Arithmetic Ops & Universal Functions

In [23]:
v = np.arange(5)
print('exp', np.exp(v))
print('sin', np.sin(v))
print('vectorised addition', v + 10)


exp [ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
sin [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
vectorised addition [10 11 12 13 14]


In [25]:
# 🖊️ TODO: given degrees [0,30,45,60,90], compute radians and sin values.
array1=np.array([0,30,45,60,90])
rad = np.deg2rad(array1)
sin_val = np.sin(array1)
print(rad)
print(sin_val)


[0.         0.52359878 0.78539816 1.04719755 1.57079633]
[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]


## <a name='broadcast'></a>8️⃣ Broadcasting Rules

Rules: compare dimensions from right → left; stretch size 1 dims; mismatch error.

In [26]:
row = np.arange(5)
col = np.arange(3).reshape(3,1)
matrix = row + col  # broadcast to 3×5
print(matrix)


[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]]


In [27]:
# 🖊️ TODO: use broadcasting to create a 10×10 multiplication table.
table=np.arange(1,11).reshape(10,1)*np.arange(1,11)
print("Multiplication table:",table)

Multiplication table: [[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


## <a name='stats'></a>9️⃣ Statistics & Aggregations

In [29]:
data = np.random.default_rng(0).integers(1, 100, size=(5,4))
print('data\n', data)
print('row sums', data.sum(axis=1))
print('col means', data.mean(axis=0))


data
 [[85 64 51 27]
 [31  5  8  2]
 [18 81 65 91]
 [50 61 97 73]
 [63 54 56 93]]
row sums [227  46 255 281 266]
col means [49.4 53.  55.4 57.2]


In [31]:
# 🖊️ TODO: compute `np.percentile` (25th, 50th, 75th) of flattened `data`.
percentile1=np.percentile(data,[25,50,75])
print("25th, 50th, 75th percentiles:", percentile1)

25th, 50th, 75th percentiles: [30.  58.5 75. ]


## <a name='random'></a>🔟 Random Numbers & Reproducibility

In [32]:
rng = np.random.default_rng(42)
rand_floats = rng.random(5)
rand_ints = rng.integers(low=10, high=50, size=5)
print(rand_floats, rand_ints)
rng2 = np.random.default_rng(42)
assert np.allclose(rand_floats, rng2.random(5))


[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735] [31 49 39 40 38]


In [34]:
# 🖊️ TODO: simulate rolling a fair six‑sided die 100 times; estimate proportion of 6s.
samples=rng.integers(1,7,100)
estimate=np.mean(samples==6)
print("Proportion of 6s:",estimate)

Proportion of 6s: 0.12


## <a name='structured'></a>1️⃣1️⃣ Structured / Record Arrays

In [35]:
people = np.array([('Alice', 25, 55.0), ('Bob', 30, 85.5)],
                   dtype=[('name','U10'), ('age','i4'), ('weight','f4')])
print(people['name'], people['age'].mean())


['Alice' 'Bob'] 27.5


In [37]:
# 🖊️ TODO: add a new field 'height' to the structured array using `np.lib.recfunctions.append_fields` (hint: pip install?).
from numpy.lib import recfunctions as rfn
heights = np.array([6.0, 5.7])
people_height= rfn.append_fields(people, 'height', heights, usemask=False)
print(people_height)

[('Alice', 25, 55. , 6. ) ('Bob', 30, 85.5, 5.7)]


## <a name='linalg'></a>1️⃣2️⃣ Linear Algebra Essentials

In [38]:
A = np.random.random((3,3))
b = np.random.random(3)
x = np.linalg.solve(A, b)
print('A·x ≈ b?', np.allclose(A.dot(x), b))


A·x ≈ b? True


In [42]:
# 🖊️ TODO: compute eigenvalues of `A` using `np.linalg.eig`.
eigval, eigvec = np.linalg.eig(A)

print("A", A)
print("Eigenvalues", eigval)



A [[0.60323476 0.2402743  0.64519298]
 [0.58244109 0.59983987 0.38206795]
 [0.94744312 0.36612423 0.89753361]]
Eigenvalues [ 1.78329868 -0.04258759  0.35989716]


## <a name='io'></a>1️⃣3️⃣ File I/O (`npy`, `npz`, `txt`)

In [43]:
np.save('array.npy', A)
loaded = np.load('array.npy')
print('loaded equals A?', np.allclose(loaded, A))
np.savez('multi_arrays.npz', A=A, b=b)


loaded equals A? True


In [44]:
# 🖊️ TODO: Use `np.savetxt` to write `data` (from stats section) to CSV then reload with `np.loadtxt`.
np.savetxt('data.csv', data, delimiter=',', fmt='%d')
loaded_csv = np.loadtxt('data.csv', delimiter=',', dtype=int)
print("Loaded CSV equals data?", np.array_equal(loaded_csv, data))

Loaded CSV equals data? True


## <a name='datetime'></a>1️⃣4️⃣ Datetime64 & Timedelta64

In [45]:
dates = np.arange('2023-01', '2023-04', dtype='datetime64[D]')
delta = dates[1:] - dates[:-1]
print(dates[:5], delta[0])


['2023-01-01' '2023-01-02' '2023-01-03' '2023-01-04' '2023-01-05'] 1 days


In [46]:
# 🖊️ TODO: find how many Mondays appear in `dates` array.
mondays = np.sum(dates.astype('datetime64[D]').view('int64') % 7 == 0)
print("Number of Mondays:", mondays)


Number of Mondays: 13


## <a name='mask'></a>1️⃣5️⃣ Masked Arrays & NaNs

In [47]:
arr = np.array([1, 2, np.nan, 4, np.nan])
masked = np.ma.masked_invalid(arr)
print(masked.mean())


2.3333333333333335


In [48]:
# 🖊️ TODO: replace NaNs with column means in a 2‑D array containing NaNs.
arr2d = np.array([[1, np.nan, 3],
                  [4, 5, np.nan],
                  [7, 8, 9]], dtype=float)
col_means = np.nanmean(arr2d, axis=0)
inds = np.where(np.isnan(arr2d))
arr2d[inds] = np.take(col_means, inds[1])
print(arr2d)


[[1.  6.5 3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]


## <a name='project'></a>1️⃣6️⃣ Mini‑Project: Fitness Data Analysis

Load `fitness.txt` (tab‑separated) then follow prompts.

In [58]:
fitness = np.genfromtxt('fitness (1).txt', delimiter='\t', dtype=None, encoding=None, names=True)
print('columns:', fitness.dtype.names, 'rows:', len(fitness))


columns: ('date', 'step_count', 'mood', 'calories_burned', 'hours_of_sleep', 'bool_of_active', 'weight_kg') rows: 96


In [59]:
# 🖊️ TODO: Monthly step count, sleep vs mood correlation, weekly summary, etc.
months = np.array([d[:7] for d in fitness['date']])
unique_months = np.unique(months)
for m in unique_months:
    total_steps = fitness['step_count'][months == m].sum()
    print(f"Month {m}: Total steps = {total_steps}")

sleep_mood_corr = np.corrcoef(fitness['hours_of_sleep'], fitness['mood'])[0,1]
print("Sleep vs mood correlation:", sleep_mood_corr)

# Weekly summary
import pandas as pd
dates_pd = pd.to_datetime(fitness['date'], format="%d-%m-%Y")
weeks = dates_pd.values.astype('datetime64[W]')
unique_weeks = np.unique(weeks)
for w in unique_weeks:
    avg_steps = fitness['step_count'][weeks == w].mean()
    print(f"Week {w}: Avg steps = {avg_steps}")

Month 01-01-2: Total steps = 299
Month 01-11-2: Total steps = 4435
Month 01-12-2: Total steps = 774
Month 02-01-2: Total steps = 1447
Month 02-11-2: Total steps = 4779
Month 02-12-2: Total steps = 1421
Month 03-01-2: Total steps = 2599
Month 03-11-2: Total steps = 1831
Month 03-12-2: Total steps = 4064
Month 04-01-2: Total steps = 702
Month 04-11-2: Total steps = 2255
Month 04-12-2: Total steps = 2725
Month 05-01-2: Total steps = 133
Month 05-11-2: Total steps = 539
Month 05-12-2: Total steps = 5934
Month 06-01-2: Total steps = 153
Month 06-10-2: Total steps = 5464
Month 06-11-2: Total steps = 5464
Month 06-12-2: Total steps = 1867
Month 07-01-2: Total steps = 500
Month 07-10-2: Total steps = 6041
Month 07-11-2: Total steps = 6041
Month 07-12-2: Total steps = 3721
Month 08-01-2: Total steps = 2127
Month 08-10-2: Total steps = 25
Month 08-11-2: Total steps = 4068
Month 08-12-2: Total steps = 2374
Month 09-01-2: Total steps = 2203
Month 09-10-2: Total steps = 5461
Month 09-11-2: Total st

## <a name='conclusion'></a>1️⃣7️⃣ Conclusion & Further Practice
Congrats on covering **all core NumPy topics** from your five lecture notebooks!

*Keep experimenting, read the official docs, and try converting your NumPy pipelines into Pandas or JAX for more fun.*